-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 14:13:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estacionamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estacionamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacionamento` DEFAULT CHARACTER SET utf8 ;
USE `estacionamento` ;

-- -----------------------------------------------------
-- Table `estacionamento`.`Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionamento`.`Vaga` (
  `idVaga` INT NOT NULL AUTO_INCREMENT,
  `numero` ENUM('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200') NOT NULL,
  `ocupado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idVaga`),
  UNIQUE INDEX `numero_vaga_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionamento`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionamento`.`Carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idCarro`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionamento`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionamento`.`Locacao` (
  `idLocacao` INT NOT NULL AUTO_INCREMENT,
  `fk_vaga` INT NOT NULL,
  `fk_carro` INT NOT NULL,
  `entrada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `saida` TIMESTAMP NULL DEFAULT NULL,
  `preco` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idLocacao`),
  INDEX `fk_Locacao_Carros_idx` (`fk_carro` ASC) VISIBLE,
  INDEX `fk_Locacao_Vaga1_idx` (`fk_vaga` ASC) VISIBLE,
  CONSTRAINT `fk_Locacao_Carro`
    FOREIGN KEY (`fk_carro`)
    REFERENCES `estacionamento`.`Carro` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Vaga`
    FOREIGN KEY (`fk_vaga`)
    REFERENCES `estacionamento`.`Vaga` (`idVaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionamento`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionamento`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `estacionamento`.`Vaga`
-- -----------------------------------------------------
START TRANSACTION;
USE `estacionamento`;
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (idVaga, ' numero',  ocupado);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (1, ' 1',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (2, ' 2',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (3, ' 3',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (4, ' 4',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (5, ' 5',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (6, ' 6',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (7, ' 7',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (8, ' 8',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (9, ' 9',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (10, ' 10',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (11, ' 11',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (12, ' 12',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (13, ' 13',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (14, ' 14',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (15, ' 15',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (16, ' 16',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (17, ' 17',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (18, ' 18',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (19, ' 19',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (20, ' 20',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (21, ' 21',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (22, ' 22',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (23, ' 23',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (24, ' 24',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (25, ' 25',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (26, ' 26',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (27, ' 27',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (28, ' 28',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (29, ' 29',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (30, ' 30',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (31, ' 31',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (32, ' 32',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (33, ' 33',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (34, ' 34',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (35, ' 35',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (36, ' 36',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (37, ' 37',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (38, ' 38',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (39, ' 39',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (40, ' 40',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (41, ' 41',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (42, ' 42',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (43, ' 43',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (44, ' 44',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (45, ' 45',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (46, ' 46',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (47, ' 47',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (48, ' 48',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (49, ' 49',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (50, ' 50',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (51, ' 51',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (52, ' 52',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (53, ' 53',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (54, ' 54',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (55, ' 55',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (56, ' 56',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (57, ' 57',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (58, ' 58',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (59, ' 59',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (60, ' 60',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (61, ' 61',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (62, ' 62',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (63, ' 63',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (64, ' 64',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (65, ' 65',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (66, ' 66',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (67, ' 67',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (68, ' 68',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (69, ' 69',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (70, ' 70',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (71, ' 71',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (72, ' 72',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (73, ' 73',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (74, ' 74',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (75, ' 75',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (76, ' 76',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (77, ' 77',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (78, ' 78',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (79, ' 79',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (80, ' 80',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (81, ' 81',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (82, ' 82',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (83, ' 83',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (84, ' 84',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (85, ' 85',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (86, ' 86',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (87, ' 87',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (88, ' 88',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (89, ' 89',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (90, ' 90',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (91, ' 91',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (92, ' 92',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (93, ' 93',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (94, ' 94',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (95, ' 95',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (96, ' 96',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (97, ' 97',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (98, ' 98',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (99, ' 99',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (100, ' 100',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (101, ' 101',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (102, ' 102',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (103, ' 103',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (104, ' 104',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (105, ' 105',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (106, ' 106',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (107, ' 107',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (108, ' 108',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (109, ' 109',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (110, ' 110',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (111, ' 111',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (112, ' 112',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (113, ' 113',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (114, ' 114',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (115, ' 115',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (116, ' 116',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (117, ' 117',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (118, ' 118',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (119, ' 119',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (120, ' 120',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (121, ' 121',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (122, ' 122',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (123, ' 123',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (124, ' 124',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (125, ' 125',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (126, ' 126',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (127, ' 127',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (128, ' 128',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (129, ' 129',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (130, ' 130',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (131, ' 131',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (132, ' 132',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (133, ' 133',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (134, ' 134',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (135, ' 135',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (136, ' 136',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (137, ' 137',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (138, ' 138',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (139, ' 139',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (140, ' 140',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (141, ' 141',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (142, ' 142',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (143, ' 143',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (144, ' 144',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (145, ' 145',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (146, ' 146',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (147, ' 147',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (148, ' 148',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (149, ' 149',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (150, ' 150',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (151, ' 151',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (152, ' 152',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (153, ' 153',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (154, ' 154',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (155, ' 155',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (156, ' 156',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (157, ' 157',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (158, ' 158',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (159, ' 159',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (160, ' 160',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (161, ' 161',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (162, ' 162',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (163, ' 163',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (164, ' 164',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (165, ' 165',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (166, ' 166',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (167, ' 167',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (168, ' 168',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (169, ' 169',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (170, ' 170',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (171, ' 171',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (172, ' 172',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (173, ' 173',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (174, ' 174',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (175, ' 175',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (176, ' 176',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (177, ' 177',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (178, ' 178',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (179, ' 179',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (180, ' 180',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (181, ' 181',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (182, ' 182',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (183, ' 183',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (184, ' 184',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (185, ' 185',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (186, ' 186',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (187, ' 187',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (188, ' 188',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (189, ' 189',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (190, ' 190',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (191, ' 191',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (192, ' 192',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (193, ' 193',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (194, ' 194',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (195, ' 195',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (196, ' 196',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (197, ' 197',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (198, ' 198',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (199, ' 199',  0);
INSERT INTO `estacionamento`.`Vaga` (`idVaga`, `numero`, `ocupado`) VALUES (200, ' 200',  0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `estacionamento`.`Admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `estacionamento`;
INSERT INTO `estacionamento`.`Admin` (`idAdmin`, `usuario`, `email`, `senha`, `cargo`) VALUES (1, 'Aguirre', 'aguirre@gmail.com', '12345678', 'Admin');
INSERT INTO `estacionamento`.`Admin` (`idAdmin`, `usuario`, `email`, `senha`, `cargo`) VALUES (2, 'Amri', 'amri@gmail.com', '12345678', 'Admin');
INSERT INTO `estacionamento`.`Admin` (`idAdmin`, `usuario`, `email`, `senha`, `cargo`) VALUES (3, 'Breno', 'breno@gmail.com', '12345678', 'Admin');
INSERT INTO `estacionamento`.`Admin` (`idAdmin`, `usuario`, `email`, `senha`, `cargo`) VALUES (4, 'Beatriz', 'beatriz@gmail.com', '12345678', 'Admin');

COMMIT;

